name: California PM Job Alerts

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  search-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Job Search
        run: python job_search.py
